name: 'EchoLayer Pipeline Import'
description: 'Import Data into EchoLayer'
inputs:
  apiPath:
    description: 'Address of the EchoLayer API'
    required: true
  apiKey:
    description: 'API Key for the EchoLayer API'
    required: true
  branch:
    description: 'The main branch of the repository'
    required: false
    default: 'main'
  pullBranchName:
    description: 'Branch name for any pull requests created'
    required: false
    default: 'EchoLayerPipeline'
  commitPrefix:
    description: 'A prefix for the commit message'
    required: false
    default: '*chore*'
  moduleGlob:
    description: 'Pattern to match the catalog-info files'
    required: false
    default: '**/catalog-info.yaml'
runs:
  using: 'node20'
  main: 'dist/index.js'
